/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.Controller;
import BLL.UserBLL;
import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JSeparator;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author Quoc An
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    Controller controller = new Controller();

    DecimalFormat formatter = new DecimalFormat("###,###,###,###");

    JSONObject jsonAll;
    JFrame frame = this;

    public Home(JSONObject json) throws ParseException {
        initComponents();

        jPanel4.putClientProperty(FlatClientProperties.STYLE, "arc: 80");
        jPanel1.putClientProperty(FlatClientProperties.STYLE, "arc: 45");
        //jPanel3.putClientProperty( FlatClientProperties.STYLE, "arc: 25" );
        jButton_nofi.putClientProperty(FlatClientProperties.STYLE, "arc: 45");
        jButton_transfer.putClientProperty(FlatClientProperties.STYLE, "arc: 45");
        jButton_1.putClientProperty(FlatClientProperties.STYLE, "arc: 45");
        jButton_qr.putClientProperty(FlatClientProperties.STYLE, "arc: 45");
        jButton_addMoney.putClientProperty(FlatClientProperties.STYLE, "arc: 45");
        jButton_history.putClientProperty(FlatClientProperties.STYLE, "arc: 45");

        jsonAll = json;
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

        System.out.println(json);
        jLabel_email.setText(json.getString("email"));
        jLabel_email1.setText(json.getString("email"));

        jLabel_balance.setText(formatter.format(json.getInt("money")) + " VNĐ");

        //DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        getRecentTransactions(json.getString("email"));
        jButton_addMoney.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new addMoney(json).setVisible(true);
            }
        });
        jButton_transfer.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new TranferMoney(json).setVisible(true);
            }
        });
        jButton_history.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    new Transactions(json).setVisible(true);
                } catch (ParseException ex) {
                    java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton_transfer = new javax.swing.JButton();
        jButton_history = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton_1 = new javax.swing.JButton();
        jButton_qr = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_balance = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_addMoney = new javax.swing.JButton();
        jLabel_email1 = new javax.swing.JLabel();
        jLabel_email = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton_nofi = new javax.swing.JButton();
        jButton_logout = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel3.setBackground(new java.awt.Color(237, 48, 54));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(26, 26, 26));
        jLabel3.setText("Utilities");

        jButton_transfer.setBackground(new java.awt.Color(237, 48, 54));
        jButton_transfer.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton_transfer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/2.png"))); // NOI18N
        jButton_transfer.setBorder(null);
        jButton_transfer.setBorderPainted(false);
        jButton_transfer.setFocusPainted(false);
        jButton_transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_transferActionPerformed(evt);
            }
        });

        jButton_history.setBackground(new java.awt.Color(237, 48, 54));
        jButton_history.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton_history.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/history.png"))); // NOI18N
        jButton_history.setBorder(null);
        jButton_history.setBorderPainted(false);
        jButton_history.setFocusPainted(false);
        jButton_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_historyActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(26, 26, 26));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Transfer");

        jLabel7.setForeground(new java.awt.Color(26, 26, 26));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Money");

        jLabel8.setForeground(new java.awt.Color(26, 26, 26));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Transactions");

        jLabel9.setForeground(new java.awt.Color(26, 26, 26));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("History");

        jButton_1.setBackground(new java.awt.Color(237, 48, 54));
        jButton_1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/wallet.png"))); // NOI18N
        jButton_1.setBorder(null);
        jButton_1.setBorderPainted(false);
        jButton_1.setFocusPainted(false);
        jButton_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_1ActionPerformed(evt);
            }
        });

        jButton_qr.setBackground(new java.awt.Color(237, 48, 54));
        jButton_qr.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton_qr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/qr.png"))); // NOI18N
        jButton_qr.setBorder(null);
        jButton_qr.setBorderPainted(false);
        jButton_qr.setFocusPainted(false);
        jButton_qr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_qrActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(26, 26, 26));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Payment");

        jLabel11.setForeground(new java.awt.Color(26, 26, 26));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("By QR");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(26, 26, 26));
        jLabel5.setText("Recent Transactions");

        jLabel12.setForeground(new java.awt.Color(26, 26, 26));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Account");

        jLabel13.setForeground(new java.awt.Color(26, 26, 26));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Manage");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_transfer, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_history, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton_qr, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jButton_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_history, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_transfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_qr, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel7))
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(233, 233, 233)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(26, 26, 26));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Balance");

        jLabel_balance.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel_balance.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_balance.setText("0");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("**** **** **** 3456");

        jButton_addMoney.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_addMoney.setText("+");
        jButton_addMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addMoneyActionPerformed(evt);
            }
        });

        jLabel_email1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_email1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_email1.setText("email");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_email1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_balance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_addMoney)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_balance)
                    .addComponent(jButton_addMoney))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel_email1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18))
        );

        jLabel_email.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel_email.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_email.setText("email");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Good morning");

        jButton4.setBackground(new java.awt.Color(237, 48, 54));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/user.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton_nofi.setBackground(new java.awt.Color(255, 255, 255));
        jButton_nofi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/nofi.png"))); // NOI18N
        jButton_nofi.setFocusPainted(false);
        jButton_nofi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nofiActionPerformed(evt);
            }
        });

        jButton_logout.setBackground(new java.awt.Color(255, 255, 255));
        jButton_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/logout.png"))); // NOI18N
        jButton_logout.setFocusPainted(false);
        jButton_logout.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/logout.png"))); // NOI18N
        jButton_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel_email, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_nofi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel_email))
                    .addComponent(jButton4)
                    .addComponent(jButton_nofi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLayeredPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_transferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_transferActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_transferActionPerformed

    private void jButton_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_historyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_historyActionPerformed

    private void jButton_addMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addMoneyActionPerformed
        // TODO add your handling code here:
        this.dispose();


    }//GEN-LAST:event_jButton_addMoneyActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_1ActionPerformed

    private void jButton_qrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_qrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_qrActionPerformed

    private void jButton_nofiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nofiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_nofiActionPerformed

    private void jButton_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logoutActionPerformed
        // TODO add your handling code here:

        JSONObject jsonSend = new JSONObject();

        jsonSend.put("email", jsonAll.getString("email"));
        jsonSend.put("func", "logout");

        String dataReceive = "";
        try {
            dataReceive = controller.SendReceiveData(jsonSend.toString());
        } catch (Exception ex) {
            //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(dataReceive);

        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_jButton_logoutActionPerformed

    private void setDataToTable(JSONArray jSONArray, DefaultTableModel model, String email) throws ParseException {
        for (int i = 0; i < jSONArray.length(); i++) {
            JSONObject jOBJ = jSONArray.getJSONObject(i);
            String total = null;

            String dateString = String.valueOf(jOBJ.get("date"));
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat dateFormat1 = new SimpleDateFormat("dd/MM/yyyy");
            Date date = dateFormat.parse(dateString);

            if (email.equals(jOBJ.get("sender"))) {
                total = " - " + formatter.format(jOBJ.get("total"));
            } else {
                total = " + " + formatter.format(jOBJ.get("total"));
            }
            Object[] row = {jOBJ.get("transaction_id").toString(),
                jOBJ.get("note").toString(),
                total, dateFormat1.format(date)};
            //add exam to each row
            model.addRow(row);
        }
    }

    private void getRecentTransactions(String email) throws ParseException {
        JSONObject jsonSend = new JSONObject();

        jsonSend.put("email", email);
        jsonSend.put("func", "getRecentTransactions");
        String dataReceive = "";
        try {
            dataReceive = controller.SendReceiveData(jsonSend.toString());
        } catch (Exception ex) {
            //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        JSONObject json = new JSONObject(dataReceive);

        JSONArray arrayTransaction = json.getJSONArray("transactionList");
        jsonAll.put("transactionList", arrayTransaction);

//        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
//            @Override
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                int row = jTable1.rowAtPoint(evt.getPoint());
//                String s = jTable1.getModel().getValueAt(row, 0) + "";
//                int id = Integer.parseInt(s);
//                   for (int i = 0; i < arrayTransaction.length(); i++) {
//                    JSONObject jOBJ = arrayTransaction.getJSONObject(i);
//                    if(jOBJ.getInt("transaction_id") == id){
//                        try {
//                            new Transaction_Detail(jOBJ).setVisible(true);
//                        } catch (ParseException ex) {
//                            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
//                        }
//                        
//                        
//                    }
//                    
//   
//                }
//            }
//        });
        // show recent 3 transactions
        int y = 190;
        JSeparator line0 = new JSeparator();
        line0.setBounds(35, 190, 320, 5);
        line0.setForeground(Color.white);
        jPanel4.add(line0);

        int n = 3;
        if (arrayTransaction.length() < 3) {
            n = arrayTransaction.length();
        }

        for (int i = 0; i < n; i++) {
            JSONObject jOBJ = arrayTransaction.getJSONObject(i);

            JLabel jlabel_icon = new JLabel();
            JLabel jlabel_text = new JLabel();
            JLabel jlabel_total = new JLabel();

            if (jOBJ.getString("sender").equals(json.getString("email"))) {
                jlabel_text.setText("Transfer to " + jOBJ.getString("receiver"));
                jlabel_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/out.png")));
                jlabel_total.setText(" - " + formatter.format(jOBJ.get("total")));
            } else if (jOBJ.getString("receiver").equals(json.getString("email"))) {
                jlabel_text.setText("Receive from " + jOBJ.getString("sender"));
                jlabel_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/in.png")));
                jlabel_total.setText(" + " + formatter.format(jOBJ.get("total")));
                jlabel_text.setForeground(Color.decode("#1AC593"));
                jlabel_total.setForeground(Color.decode("#1AC593"));
            }

            jlabel_text.addMouseListener(new MouseAdapter() {
                public void mouseClicked(MouseEvent e) {

                    try {
                        new Transaction_Detail(jOBJ).setVisible(true);
                    } catch (ParseException ex) {
                        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            });

            String dateString = String.valueOf(jOBJ.get("date"));
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat dateFormat1 = new SimpleDateFormat("dd/MM/yyyy");
            Date date = dateFormat.parse(dateString);

            // JLabel jlabel_icon = new JLabel();
            //jlabel_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/in.png")));
            JLabel jlabel_date = new JLabel(dateFormat1.format(date));
            jlabel_total.setHorizontalAlignment(SwingConstants.TRAILING);
            jPanel4.add(jlabel_text);
            jPanel4.add(jlabel_icon);
            jPanel4.add(jlabel_date);
            jPanel4.add(jlabel_total);

            jlabel_icon.setBounds(20, y + 10, 24, 24);

            jlabel_total.setBounds(215, y + 20, 150, 20);

            jlabel_text.setBounds(45, y + 12, 250, 20);

            jlabel_date.setBounds(45, y + 33, 100, 15);

            jlabel_date.setForeground(Color.black);
            jlabel_date.setFont(new Font("Segoe UI", Font.ITALIC, 13));

            jlabel_text.setFont(new Font("Segoe UI", Font.BOLD, 15));

            jlabel_total.setFont(new Font("Segoe UI", Font.BOLD, 15));

            JSeparator line = new JSeparator();
            line.setBounds(35, y + 60, 320, 5);
            line.setForeground(Color.LIGHT_GRAY);
            jPanel4.add(line);
            y += 60;

        }
        //setDataToTable(arrayTransaction, model, json.getString("email"));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Home(json).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_1;
    private javax.swing.JButton jButton_addMoney;
    private javax.swing.JButton jButton_history;
    private javax.swing.JButton jButton_logout;
    private javax.swing.JButton jButton_nofi;
    private javax.swing.JButton jButton_qr;
    private javax.swing.JButton jButton_transfer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_balance;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_email1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
